[macd.parameters]
#short = "10..20:2"
#long = "21..61:10"
short = 18
long = 21
signal=10
#signal = "9..15:1"

[macd.thresholds]
down = -0.96
up = 0.2
persistence = 1

#0.045|1|-0.015
[macd.chart]
showInExtraWindow = true
type="macd"
