[cci.parameters]
optInTimePeriod = 20
#18
[cci.thresholds]
up = 20
down = -70
down_extreme=-170

[smaLong.parameters]
optInTimePeriod = 200
[smaMiddle.parameters]
optInTimePeriod = 15
[smaShort.parameters]
optInTimePeriod = 7

[aroonosc.parameters]
optInTimePeriod = 20
#18
[aroonosc.thresholds]
up = 10
down = -10
