[cci.parameters]
optInTimePeriod = 20
[cci.thresholds]
up_extreme = 170
up = 70
down = -20

[smaLong.parameters]
optInTimePeriod = 100
[smaMiddle.parameters]
optInTimePeriod = 21
[smaShort.parameters]
optInTimePeriod = 7


####################
[adx.parameters]
optInTimePeriod = 20
#"10..30:1"
[adx.thresholds]
up = 25
down = 20

[aroonosc.parameters]
optInTimePeriod = 100
[aroonosc.thresholds]
up = 55
down = 20
